# Generated by Django 6.0.5 on 2026-08-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_marketsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualFundDataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(help_text="e.g. Childrens Fund", max_length=255),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Greater than 1 Year", "Greater than 1 Year"),
                            ("Less than 1 Year", "Less than 1 Year"),
                        ],
                        max_length=100,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/mutual_funds/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MutualFundPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=255)),
                ("period", models.CharField(db_index=True, max_length=100)),
                ("scheme_name", models.CharField(max_length=512)),
                (
                    "nav",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("launch_date", models.DateField(blank=True, null=True)),
                (
                    "aum_crore",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "ber_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ter_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "ytd_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_1w",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_1m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_3m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_6m",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "return_1yr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("rank_1yr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "return_2yr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("rank_2yr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "return_3yr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("rank_3yr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "return_5yr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("rank_5yr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "return_10yr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("rank_10yr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "fund_manager",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "period"],
                        name="api_mutualf_categor_fa1e8b_idx",
                    )
                ],
            },
        ),
    ]
