# Generated by Django 6.0.5 on 2026-09-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mutualfunddataupload_mutualfundperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='naventry',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='naventry',
            name='isin_div_payout_growth',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='naventry',
            name='isin_div_reinvestment',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='naventry',
            index=models.Index(fields=['company_name', 'nav_date'], name='api_naventr_company_854e42_idx'),
        ),
    ]
