# Generated by Django 6.0.5 on 2026-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emailsubscriber_interests_emailsubscriber_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mutualfundperformance',
            name='api_mutualf_categor_fa1e8b_idx',
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='alpha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='sharpe_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundperformance',
            name='std_deviation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddataupload',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Equity: ELSS (leave blank to auto-detect from Excel)', max_length=255),
        ),
        migrations.AlterField(
            model_name='mutualfunddataupload',
            name='period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mutualfundperformance',
            name='period',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='mutualfundperformance',
            index=models.Index(fields=['category'], name='api_mutualf_categor_30c8d4_idx'),
        ),
    ]
