# Generated by Django 6.0.5 on 2026-09-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_mutualfundperformance_api_mutualf_categor_fa1e8b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfunddataupload',
            name='period',
        ),
        migrations.RemoveField(
            model_name='mutualfundperformance',
            name='period',
        ),
    ]
