# Generated by Django 6.0.5 on 2026-09-27 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_mutualfunddataupload_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referer', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveIntegerField(db_index=True, default=200)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='api_pagevis_path_a15211_idx'), models.Index(fields=['status_code', 'created_at'], name='api_pagevis_status__103744_idx')],
            },
        ),
    ]
